server:
	g++ chatting_server.cpp src/server.cpp src/terminal.cpp src/lfu_cache.cpp -o build/chatting_server -std=c++0x
client:
	g++ chatting_client.cpp src/client.cpp src/terminal.cpp src/lfu_cache.cpp -o build/chatting_client -std=c++0x
